EnableDefaultLinters: true

glob: '**/*.erb'

exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**/*'

linters:
  ErbSafety:
    enabled: true

  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/LineLength:
        Enabled: false
      Style/StringLiterals:
        EnforcedStyle: single_quotes
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false

  SpaceAroundErbTag:
    enabled: true

  ClosingErbTagIndent:
    enabled: true

  FinalNewline:
    enabled: true

  TrailingWhitespace:
    enabled: true
